# Generated by Django 4.2.9 on 2024-07-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_category_post_quesmodel_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
